Repository bangumi/frontend, pull requests merged in 2022-12, with the labels that each got.

#113 feat(website): implement group topic page
  .eslintrc.js
  jest.config.js
  packages/client/common.ts
  packages/client/group.ts
  packages/client/topic.ts
  packages/client/user.ts
  packages/design/components/Avatar/Avatar.stories.tsx
  packages/design/components/Avatar/style/index.less
  packages/design/components/EditorForm/style/index.less
  packages/design/components/Layout/Layout.stories.tsx
  packages/design/components/Layout/index.tsx
  packages/design/components/Layout/style/index.less
  packages/design/components/Layout/style/index.tsx
  packages/design/components/Pagination/index.tsx
  packages/design/components/RichContent/index.tsx
  packages/design/components/RichContent/style/index.less
  packages/design/components/Section/index.tsx
  packages/design/components/Topic/Comment.stories.tsx
  packages/design/components/Topic/Comment.tsx
  packages/design/components/Topic/CommentInfo.tsx
  packages/design/components/Topic/__test__/Comment.spec.tsx
  packages/design/components/Topic/__test__/CommentInfo.spec.tsx
  packages/design/components/Topic/__test__/__snapshots__/Comment.spec.tsx.snap
  packages/design/components/Topic/__test__/fixtures/repliesComment.json
  packages/design/components/Topic/__test__/fixtures/singleComment.json
  packages/design/components/Topic/__test__/fixtures/specialComment.json
  packages/design/components/Topic/__test__/fixtures/user.json
  packages/design/components/Topic/index.tsx
  packages/design/components/Topic/style/Comment.less
  packages/design/components/Topic/style/CommentInfo.less
  packages/design/components/Topic/style/index.tsx
  packages/design/index.tsx
  packages/design/package.json
  packages/icons/assets/friend.svg
  packages/icons/assets/original-poster.svg
  packages/icons/assets/topic-closed.svg
  packages/icons/assets/topic-reopen.svg
  packages/icons/assets/topic-silent.svg
  packages/icons/index.tsx
  packages/utils/pages.ts
  packages/website/src/hooks/use-group-topic.ts
  packages/website/src/hooks/use-group.ts
  packages/website/src/pages/components/UserHome.tsx
  packages/website/src/pages/index/group/[name]/components/TopicsTable.tsx
  packages/website/src/pages/index/group/[name]/forum.tsx
  packages/website/src/pages/index/group/[name]/index.tsx
  packages/website/src/pages/index/group/[name]/members.module.less
  packages/website/src/pages/index/group/[name]/members.tsx
  packages/website/src/pages/index/group/[name]/style.module.less
  packages/website/src/pages/index/group/components/ClampableContent.module.less
  packages/website/src/pages/index/group/components/ClampableContent.tsx
  packages/website/src/pages/index/group/components/GroupLayout.module.less
  packages/website/src/pages/index/group/components/GroupLayout.tsx
  packages/website/src/pages/index/group/components/UserCard.tsx
  packages/website/src/pages/index/group/topic/[id].tsx
  packages/website/src/pages/index/group/topic/[id]/components/GroupTopicHeader.module.less
  packages/website/src/pages/index/group/topic/[id]/components/GroupTopicHeader.tsx
  packages/website/src/pages/index/group/topic/[id]/index.module.less
  packages/website/src/pages/index/group/topic/[id]/index.tsx
  pnpm-lock.yaml
Labels: size/XXL

#229 tests: fix ref warning
  packages/website/src/pages/login/index.spec.tsx
  packages/website/src/pages/login/index.tsx
Labels: size/S

#245 build: update deps
  package.json
  packages/client/package.json
  packages/design/package.json
  packages/icons/package.json
  packages/utils/package.json
  packages/website/package.json
  pnpm-lock.yaml
Labels: size/XXL

#246 chore(deps): bump swr from 1.3.0 to 2.0.0
  packages/design/components/Topic/__test__/Comment.spec.tsx
  packages/website/package.json
  packages/website/src/hooks/use-user.tsx
  pnpm-lock.yaml
Labels: size/XL

#247 refactor: replace hcaptcha with turnstile
  .github/workflows/build.yml
  packages/website/.env
  packages/website/.env.production
  packages/website/package.json
  packages/website/src/hooks/use-user.spec.tsx
  packages/website/src/hooks/use-user.tsx
  packages/website/src/pages/login/index.spec.tsx
  packages/website/src/pages/login/index.tsx
  packages/website/src/vite-env.d.ts
  packages/website/vite.config.ts
  pnpm-lock.yaml
Labels: size/XL

#244 build: enable source map
  .gitignore
  packages/design/.storybook/main.ts
  packages/design/components/Avatar/index.tsx
  packages/design/components/Button/index.tsx
  packages/design/components/Divider/index.tsx
  packages/design/components/EditorForm/index.tsx
  packages/design/components/Image/index.tsx
  packages/design/components/Input/index.tsx
  packages/design/components/Layout/index.tsx
  packages/design/components/Menu/index.tsx
  packages/design/components/Pagination/index.tsx
  packages/design/components/Rate/index.tsx
  packages/design/components/RichContent/index.tsx
  packages/design/components/Section/index.tsx
  packages/design/components/Tab/index.tsx
  packages/design/components/Topic/index.tsx
  packages/design/components/Typography/index.tsx
  packages/website/package.json
  packages/website/vite.config.ts
  pnpm-lock.yaml
Labels: size/M

#256 feat: group topic reply
  packages/design/components/EditorForm/Editor.tsx
  packages/design/components/EditorForm/EditorForm.stories.tsx
  packages/design/components/EditorForm/Toolbox.tsx
  packages/design/components/EditorForm/__test__/Editor.spec.tsx
  packages/design/components/EditorForm/__test__/EditorForm.test.tsx
  packages/design/components/EditorForm/index.tsx
  packages/design/components/Topic/Comment.tsx
  packages/design/components/Topic/CommentInfo.tsx
  packages/design/components/Topic/ReplyForm.tsx
  packages/design/components/Topic/__test__/Comment.spec.tsx
  packages/design/package.json
  packages/website/src/hooks/use-group-topic.ts
  packages/website/src/hooks/use-group.ts
  packages/website/src/pages/index/group/topic/[id]/components/GroupTopicHeader.tsx
  packages/website/src/pages/index/group/topic/[id]/index.tsx
  pnpm-lock.yaml
Labels: size/XL

#270 feat: show tip for toolbox icons
  packages/design/components/EditorForm/Toolbox.tsx
  packages/design/components/EditorForm/__test__/__snapshots__/Editor.spec.tsx.snap
  packages/design/components/EditorForm/__test__/__snapshots__/EditorForm.test.tsx.snap
  packages/design/components/EditorForm/__test__/__snapshots__/Toolbox.spec.tsx.snap
  packages/website/vite.config.ts
Labels: size/XS

#268 ci: adjust codecov requirement
  .github/codecov.yaml
Labels: size/XS

#274 fix: storybook typo & doc
  packages/design/components/Avatar/index.tsx
  packages/design/components/Divider/index.tsx
  packages/design/components/Image/index.tsx
  packages/design/components/Input/index.tsx
  packages/design/components/Menu/MenuItem.tsx
  packages/design/components/Menu/index.tsx
  packages/design/components/Pagination/index.tsx
  packages/design/components/Rate/index.tsx
  packages/design/components/Tab/index.tsx
  packages/design/components/Typography/Link.stories.tsx
  packages/design/components/Typography/Typography.stories.tsx
Labels: size/S

#277 fix: remove `dangerouslySetInnerHTML`
  .prettierignore
  packages/design/components/RichContent/RichContent.stories.tsx
  packages/design/components/RichContent/index.tsx
  packages/design/components/Topic/Comment.tsx
  packages/utils/bbcode/__test__/__snapshots__/html.test.ts.snap
  packages/utils/bbcode/__test__/__snapshots__/react.test.tsx.snap
  packages/utils/bbcode/__test__/convert.test.ts
  packages/utils/bbcode/__test__/html.test.ts
  packages/utils/bbcode/__test__/react.test.tsx
  packages/utils/bbcode/convert.ts
  packages/utils/bbcode/index.ts
  packages/utils/bbcode/react.tsx
  packages/utils/package.json
  packages/website/src/pages/index/group/components/ClampableContent.tsx
  packages/website/src/pages/index/group/topic/[id]/index.tsx
  pnpm-lock.yaml
Labels: size/L
