Repository bangumi/frontend, pull requests merged in 2022-11, with the labels that each got.

#223 chore: fix vite proxy to prod server
  packages/website/vite.config.ts
Labels: size/XS

#183 feat(website): customize router link
  packages/website/src/App.tsx
  packages/website/src/components/Header/index.tsx
  packages/website/src/components/Link/index.tsx
  packages/website/src/pages/index/group/[name]/__tests__/index.spec.tsx
  packages/website/src/utils/test-utils.tsx
Labels: size/M

#225 fix: reset hcaptcha when login failed
  packages/website/src/pages/login/index.tsx
Labels: size/XS

#227 style: add eslint rule `no-else-return`
  .eslintrc.js
  packages/design/components/Divider/Divider.stories.tsx
  packages/utils/bbcode/convert.ts
  packages/utils/bbcode/html.ts
  packages/utils/bbcode/parser.ts
  packages/utils/wiki/parser.ts
  packages/website/src/pages/index/group/[name]/components/ClampableContent.tsx
Labels: size/M

#231 fix(design): test type and `include` of tsconfig
  packages/design/components/Avatar/__test__/Avatar.test.tsx
  packages/design/components/Button/__test__/Button.test.tsx
  packages/design/components/Typography/__test__/Texts.spec.tsx
  packages/website/tsconfig.json
Labels: size/S

#226 fix: `(bgm11)` url
  packages/design/components/RichContent/RichContent.stories.tsx
  packages/design/package.json
  packages/utils/bbcode/__test__/html.test.ts
  packages/utils/bbcode/convert.ts
  pnpm-lock.yaml
Labels: size/M
