Repository bangumi/frontend, pull requests merged in 2023-01, with the labels that each got.

#269 feat: highlight comment by hash
  packages/design/components/Topic/Comment.tsx
  packages/design/components/Topic/__test__/Comment.spec.tsx
  packages/design/components/Topic/__test__/__snapshots__/Comment.spec.tsx.snap
  packages/design/components/Topic/style/Comment.less
  packages/website/src/pages/index/group/topic/[id]/index.tsx
Labels: size/S

#294 chore: use stage api as default backend
  .github/workflows/build.yml
  CONTRIBUTING.md
  packages/website/vite.config.ts
Labels: size/XS

#293 chore: add a tracking dashboard
  CONTRIBUTING.md
Labels: size/XS

#296 chore: remove data-testid in prod
  packages/website/package.json
  packages/website/vite.config.ts
  pnpm-lock.yaml
Labels: size/XS

#298 ci: fix preview captcha
  .github/workflows/build.yml
  packages/website/package.json
Labels: size/XS

#278 fix: comment quote style
  .stylelintrc.js
  packages/design/components/RichContent/style/index.less
  packages/design/components/Topic/style/Comment.less
  packages/icons/assets/close-quote.svg
  packages/icons/assets/open-quote.svg
  packages/icons/index.tsx
Labels: size/S

#301 feat(design): toast
  packages/design/components/Toast/Toast.stories.tsx
  packages/design/components/Toast/Toast.tsx
  packages/design/components/Toast/ToastContainer.tsx
  packages/design/components/Toast/__test__/Toast.spec.tsx
  packages/design/components/Toast/__test__/ToastContainer.spec.tsx
  packages/design/components/Toast/index.tsx
  packages/design/components/Toast/style/index.less
  packages/design/components/Toast/style/index.tsx
  packages/design/components/Toast/types.ts
  packages/design/components/Toast/utils/event-bus.ts
  packages/design/package.json
  pnpm-lock.yaml
Labels: size/M

#304 refactor: update colors
  packages/design/components/Input/Input.stories.tsx
  packages/design/components/Menu/style/index.less
  packages/design/theme/variables.less
  packages/icons/assets/bold.svg
  packages/icons/assets/captcha.svg
  packages/icons/assets/close-quote.svg
  packages/icons/assets/delete.svg
  packages/icons/assets/empty-star.svg
  packages/icons/assets/expand.svg
  packages/icons/assets/half-star.svg
  packages/icons/assets/image.svg
  packages/icons/assets/italic.svg
  packages/icons/assets/link.svg
  packages/icons/assets/notification.svg
  packages/icons/assets/open-quote.svg
  packages/icons/assets/password.svg
  packages/icons/assets/search.svg
  packages/icons/assets/setting.svg
  packages/icons/assets/size.svg
  packages/icons/assets/topic-silent.svg
  packages/icons/assets/underscore.svg
  packages/icons/assets/user-login.svg
  packages/website/src/assets/down-arrow.svg
  packages/website/src/assets/right-arrow.svg
  packages/website/src/assets/up-arrow.svg
  packages/website/src/components/Header/style.module.less
Labels: size/S

#308 style: add eslint plugin to ensure import sorting
  .eslintrc.js
  package.json
  packages/client/client.ts
  packages/design/.storybook/main.ts
  packages/design/.storybook/preview.ts
  packages/design/components/Divider/Divider.stories.tsx
  packages/design/components/EditorForm/Editor.tsx
  packages/design/components/EditorForm/EditorForm.stories.tsx
  packages/design/components/EditorForm/__test__/EditorForm.test.tsx
  packages/design/components/Image/Image.stories.tsx
  packages/design/components/Input/Input.stories.tsx
  packages/design/components/Menu/Menu.stories.tsx
  packages/design/components/Pagination/Pagination.stories.tsx
  packages/design/components/Rate/index.tsx
  packages/design/components/RichContent/index.tsx
  packages/design/components/Section/index.tsx
  packages/design/components/Toast/Toast.tsx
  packages/design/components/Toast/__test__/ToastContainer.spec.tsx
  packages/design/components/Toast/index.tsx
  packages/design/components/Topic/Comment.tsx
  packages/icons/index.stories.tsx
  packages/utils/bbcode/__test__/html.test.ts
  packages/website/src/App.tsx
  packages/website/src/components/Header/SubMenu.tsx
  packages/website/src/components/Header/index.tsx
  packages/website/src/components/Link/index.tsx
  packages/website/src/hooks/use-group.ts
  packages/website/src/hooks/use-navigate.ts
  packages/website/src/main.tsx
  packages/website/src/pages/index/group/[name].tsx
  packages/website/src/pages/index/group/[name]/__tests__/members.spec.tsx
  packages/website/src/pages/index/group/[name]/index.tsx
  packages/website/src/pages/index/group/components/GroupLayout.tsx
  packages/website/src/pages/index/group/topic/[id]/components/GroupTopicHeader.tsx
  packages/website/src/pages/index/group/topic/[id]/index.tsx
  packages/website/src/pages/login/index.spec.tsx
  packages/website/src/pages/login/index.tsx
  packages/website/vite.config.ts
  pnpm-lock.yaml
Labels: size/M

#309 refactor: use eventemitter3 generic type paramaters
  packages/design/components/Toast/utils/event-bus.ts
Labels: size/XS

#302 build(website): autoprefixer
  packages/website/package.json
  packages/website/postcss.config.js
  packages/website/src/pages/login/index.module.less
  pnpm-lock.yaml
Labels: size/XS

#319 fix: BBCode rendering line breaks & react key
  packages/utils/bbcode/__test__/__snapshots__/react.test.tsx.snap
  packages/utils/bbcode/react.tsx
Labels: size/XS

#323 fix(Editor): pass down extra props, fix font size & padding
  packages/design/components/EditorForm/Editor.tsx
  packages/design/components/EditorForm/style/index.less
Labels: size/XS

#326 refactor(Editor): forward textarea ref & props
  packages/design/components/EditorForm/Editor.tsx
  packages/design/components/EditorForm/EditorForm.stories.tsx
  packages/design/components/EditorForm/__test__/Editor.spec.tsx
  packages/design/components/EditorForm/__test__/EditorForm.test.tsx
  packages/design/components/EditorForm/index.tsx
  packages/design/components/Topic/ReplyForm.tsx
Labels: size/S

#324 refactor: update button design system
  packages/design/components/Button/__test__/Button.test.tsx
  packages/design/components/Button/__test__/__snapshots__/Button.test.tsx.snap
  packages/design/components/Button/button.stories.tsx
  packages/design/components/Button/index.tsx
  packages/design/components/Button/style/index.less
  packages/design/components/EditorForm/__test__/__snapshots__/EditorForm.test.tsx.snap
  packages/design/components/EditorForm/index.tsx
  packages/design/components/EditorForm/style/index.less
  packages/design/components/Form/Form.stories.tsx
  packages/design/components/Topic/Comment.tsx
  packages/design/components/Topic/__test__/__snapshots__/Comment.spec.tsx.snap
  packages/design/components/Topic/style/Comment.less
  packages/website/src/components/Header/index.tsx
  packages/website/src/components/Header/style.module.less
  packages/website/src/pages/index/group/topic/[id]/index.module.less
  packages/website/src/pages/index/group/topic/[id]/index.tsx
  packages/website/src/pages/index/subject/[id]/wiki/common.module.less
  packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx
  packages/website/src/pages/login/index.module.less
  packages/website/src/pages/login/index.tsx
Labels: size/L
