Repository bangumi/frontend, pull requests merged in 2023-04, with the labels that each got.

#511 refactor: align GroupInfo component with design
  packages/design/components/Layout/style/index.less
  packages/website/src/pages/index/group/[name]/new_topic/index.tsx
  packages/website/src/pages/index/group/components/GroupActions.tsx
  packages/website/src/pages/index/group/components/GroupInfo.module.less
  packages/website/src/pages/index/group/components/GroupInfo.tsx
  packages/website/src/pages/index/group/components/GroupNavigation.tsx
  packages/website/src/pages/index/group/topic/[id]/index.tsx
Labels: size/S, waiting-approval

#532 ci: fix e2e test fail label
  .github/mergify.yml
  .github/workflows/e2e-test.yml
Labels: size/XS

#536 ci: add type-check
  .eslintrc.js
  .github/workflows/lint.yml
  packages/design/components/Button/button.stories.tsx
  packages/design/components/EditorForm/EditorForm.stories.tsx
  packages/design/components/Input/Input.stories.tsx
  packages/icons/index.stories.tsx
  packages/utils/wiki.ts
  packages/website/src/components/Helmet.tsx
Labels: size/S, waiting-approval

#473 feat: new notification
  packages/client/user.ts
  packages/design/theme/variables.less
  packages/icons/assets/arrow-path.svg
  packages/icons/assets/enter.svg
  packages/icons/index.tsx
  packages/website/package.json
  packages/website/src/App.tsx
  packages/website/src/components/Header/index.tsx
  packages/website/src/components/Header/style.module.less
  packages/website/src/components/Helmet.tsx
  packages/website/src/error.ts
  packages/website/src/hooks/use-notify.tsx
  packages/website/src/pages/index/group/reply/[id]/edit.tsx
  packages/website/src/pages/index/notifications/index.module.less
  packages/website/src/pages/index/notifications/index.tsx
  packages/website/src/shared/notifications.ts
  packages/website/src/style/animation.less
  packages/website/src/style/index.less
  packages/website/vite.config.ts
  pnpm-lock.yaml
Labels: size/XL, waiting-approval

#546 docs: add readme for `@bangumi/client`
  packages/client/readme.md
Labels: size/S, waiting-opened-48h

#545 refactor: adjust max content width
  packages/design/components/Layout/style/index.less
  packages/design/theme/variables.less
  packages/website/src/components/Footer/style.module.less
  packages/website/src/components/GlobalLayout/style.module.less
  packages/website/src/components/Header/index.tsx
  packages/website/src/components/Header/style.module.less
Labels: size/XS, waiting-approval

#547 build: upgrade to pnpm to v8
  .github/actions/setup-js-env/action.yaml
  package.json
  pnpm-lock.yaml
Labels: size/XS, waiting-approval
