Repository bangumi/frontend, pull requests merged in 2023-03, with the labels that each got.

#429 fix: collapse & disable reply on deleted comments
  packages/design/components/Topic/Comment.tsx
  packages/design/components/Topic/__test__/__snapshots__/Comment.spec.tsx.snap
Labels: size/M, waiting-approval

#423 fix: search select box does not display properly on safari
  packages/website/src/index.css
Labels: size/XS, waiting-approval

#428 feat: delete group reply
  packages/design/components/Topic/Comment.tsx
  packages/design/components/Topic/__test__/Comment.spec.tsx
  packages/website/src/pages/index/group/topic/[id]/index.tsx
Labels: size/XS, waiting-approval

#433 build: build js/css files with .min.[ext]
  packages/website/vite.config.ts
Labels: size/XS, waiting-approval

#431 fix: BBcode style
  packages/design/components/RichContent/style/index.less
  packages/utils/bbcode/__test__/__snapshots__/react.test.tsx.snap
  packages/utils/bbcode/__test__/convert.test.ts
  packages/utils/bbcode/__test__/html.test.ts
  packages/utils/bbcode/convert.ts
Labels: size/S, waiting-approval

#305 fix(website): show unexpected error in ErrorBoundary
  packages/design/components/Typography/Link.tsx
  packages/design/components/Typography/style/Link.less
  packages/website/src/components/ErrorBoundary.tsx
  packages/website/src/components/ErrorBoundary/ErrorLayout.tsx
  packages/website/src/components/ErrorBoundary/index.tsx
  packages/website/src/components/ErrorBoundary/style.module.less
  packages/website/src/components/GlobalLayout/style.module.less
  packages/website/src/components/NotFound.tsx
  packages/website/src/pages/index/group/[name]/index.tsx
  packages/website/src/pages/index/group/[name]/index/members.tsx
  packages/website/src/pages/index/group/[name]/new_topic.tsx
  packages/website/src/pages/index/group/[name]/new_topic/index.tsx
  packages/website/src/pages/index/group/topic/[id].tsx
  packages/website/src/pages/index/subject/[id]/wiki.tsx
  packages/website/vite.config.ts
Labels: size/M, waiting-approval

#464 chore: lock msw to `~1.0.1`
  packages/client/package.json
  packages/design/package.json
  packages/website/package.json
  pnpm-lock.yaml
Labels: size/XS

#467 chore: merge bot rule
  .github/mergify.yml
Labels: size/S, waiting-approval

#439 test: e2e test
  .github/workflows/e2e-test.yml
  .gitignore
  package.json
  packages/website/e2e/404.spec.ts
  packages/website/e2e/common/login.ts
  packages/website/e2e/group.spec.ts
  packages/website/e2e/main.spec.ts
  packages/website/package.json
  packages/website/playwright.config.ts
  packages/website/tsconfig.json
  pnpm-lock.yaml
  vitest.config.ts
Labels: size/M, waiting-approval

#468 chore: label bot rule
  .github/mergify.yml
Labels: size/XS

#469 docs: update CONTRIBUTING.md for preview url
  CONTRIBUTING.md
Labels: size/XS

#435 feat: error toast
  packages/design/components/Message/Message.stories.tsx
  packages/design/components/Message/__test__/Message.spec.tsx
  packages/design/components/Message/__test__/__snapshots__/Message.spec.tsx.snap
  packages/design/components/Message/index.tsx
  packages/design/components/Message/style/index.less
  packages/design/components/Message/style/index.tsx
  packages/design/components/Toast/Toast.stories.tsx
  packages/design/components/Toast/Toast.tsx
  packages/design/components/Toast/__test__/Toast.spec.tsx
  packages/design/components/Toast/index.tsx
  packages/design/components/Toast/style/index.less
  packages/design/components/Toast/types.ts
  packages/design/index.tsx
  packages/icons/assets/error.svg
  packages/icons/index.tsx
  packages/website/src/pages/login/components/ErrorMessage/index.module.less
  packages/website/src/pages/login/components/ErrorMessage/index.tsx
  packages/website/src/pages/login/index.tsx
Labels: size/M, waiting-approval

#466 feat: add request id in global error page
  packages/website/src/components/ErrorBoundary/ErrorLayout.tsx
  packages/website/src/components/ErrorBoundary/index.tsx
  packages/website/src/components/ErrorBoundary/style.module.less
  packages/website/src/pages/index/group/topic/[id].tsx
  packages/website/vite.config.ts
Labels: size/S, waiting-approval

#477 refactor: update openapi client
  packages/client/api.yaml
  packages/client/client.ts
  packages/client/types/index.ts
  packages/website/src/hooks/use-user.spec.tsx
  packages/website/src/hooks/use-user.tsx
  packages/website/src/pages/login/index.spec.tsx
Labels: size/M, waiting-approval

#481 ci: update and create new next milestone when release
  .github/scripts/milestone.mts
  .github/workflows/e2e-test.yml
  .github/workflows/release.yml
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: size/M, waiting-approval

#482 ci: rewrite scripts with ts
  .eslintrc.js
  .github/scripts/upload-preview.mts
  .github/workflows/preview.yaml
  package.json
Labels: size/S

#484 fix: login redirect after captcha reset
  packages/website/src/components/Header/index.tsx
  packages/website/src/pages/login/index.spec.tsx
  packages/website/src/pages/login/index.tsx
Labels: size/XS, waiting-approval

#426 feat: edit group reply
  packages/design/components/Topic/Comment.tsx
  packages/design/components/Topic/__test__/Comment.spec.tsx
  packages/website/src/hooks/use-group-post.ts
  packages/website/src/pages/index/group/reply/[id].tsx
  packages/website/src/pages/index/group/reply/[id]/edit.module.less
  packages/website/src/pages/index/group/reply/[id]/edit.tsx
Labels: size/M, waiting-approval

#503 refactor: add build hash and time
  packages/website/src/components/Footer/index.tsx
  packages/website/vite.config.ts
Labels: size/XS, waiting-approval

#506 build: remove `min` from build files
  packages/website/vite.config.ts
Labels: size/XS, waiting-approval

#507 ci: use zip to bundle release asset
  .github/workflows/release.yml
Labels: size/XS

#508 chore: switch stage api backend domain
  .github/workflows/build-next.yaml
  packages/website/public/_redirects
  packages/website/vite.config.ts
Labels: size/S, waiting-approval

#510 chore: add @y-young to Collaborators
  README.md
Labels: size/XS, waiting-opened-48h

#512 fix: set page title
  packages/website/package.json
  packages/website/src/App.tsx
  packages/website/src/components/Helmet.tsx
  packages/website/src/pages/index/group/[name]/__tests__/members.spec.tsx
  packages/website/src/pages/index/group/[name]/index/forum.tsx
  packages/website/src/pages/index/group/[name]/index/index.tsx
  packages/website/src/pages/index/group/[name]/index/members.tsx
  packages/website/src/pages/index/group/[name]/new_topic/index.tsx
  packages/website/src/pages/index/group/reply/[id]/edit.tsx
  packages/website/src/pages/index/group/topic/[id]/edit.tsx
  packages/website/src/pages/index/group/topic/[id]/index.tsx
  packages/website/src/pages/index/subject/[id]/components/WikiBeginnerEditor.spec.tsx
  packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx
  packages/website/src/pages/login/index.spec.tsx
  packages/website/src/pages/login/index.tsx
  packages/website/src/utils/test-utils.tsx
  pnpm-lock.yaml
Labels: size/L, waiting-approval
