Repository bangumi/frontend, pull requests merged in 2023-02, with the labels that each got.

#322 refactor: extract group info component
  packages/website/src/pages/index/group/components/GroupInfo.module.less
  packages/website/src/pages/index/group/components/GroupInfo.tsx
  packages/website/src/pages/index/group/topic/[id]/index.module.less
  packages/website/src/pages/index/group/topic/[id]/index.tsx
Labels: size/M

#334 add @FoundTheWOUT to Collaborators
  README.md
Labels: size/XS

#332 build: remove monaco-editor built-in languages
  packages/website/src/components/WikiEditor/WikiEditor.tsx
Labels: size/XS

#333 fix: enter key not working in form
  packages/design/components/Form/index.tsx
  packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx
Labels: size/XS

#330 refactor: custom SuspenseRouter
  packages/website/package.json
  packages/website/src/App.tsx
  packages/website/src/components/Header/index.tsx
  packages/website/src/components/Link/index.tsx
  packages/website/src/components/SuspenseRouter.tsx
  packages/website/src/hooks/use-transition-context.ts
  packages/website/src/main.tsx
  packages/website/src/pages/index/group/components/GroupLayout.tsx
  packages/website/src/pages/index/subject/[id]/components/WikiLayout.tsx
  packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx
  packages/website/src/utils/test-utils.tsx
  pnpm-lock.yaml
Labels: size/M

#335 fix: weird behaviour of Tab keydown
  packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx
Labels: size/XS

#338 fix: edit_detail typo
  packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx
Labels: size/XS

#342 fix: click logo should back to home
  packages/website/src/components/Header/index.tsx
Labels: size/XS

#343 fix: ts path intelligent
  tsconfig.json
Labels: size/XS

#336 feat: button link
  packages/design/components/Button/__test__/Button.test.tsx
  packages/design/components/Button/__test__/__snapshots__/Button.test.tsx.snap
  packages/design/components/Button/button.stories.tsx
  packages/design/components/Button/index.tsx
  packages/design/components/Button/style/index.less
  packages/design/components/Typography/Link.tsx
  packages/design/components/Typography/__test__/Link.spec.tsx
  packages/design/components/Typography/__test__/__snapshots__/Link.spec.tsx.snap
  packages/website/src/pages/index/group/components/GroupInfo.tsx
Labels: size/M

#346 ci(Mergify): configuration update
  .mergify.yml
Labels: size/XS

#344 fix: collapsed comment style
  packages/design/components/Topic/style/Comment.less
Labels: size/XS

#340 refactor: input design
  packages/design/components/Form/Form.stories.tsx
  packages/design/components/Form/style/index.less
  packages/design/components/Input/Input.stories.tsx
  packages/design/components/Input/__test__/__snapshots__/index.spec.tsx.snap
  packages/design/components/Input/__test__/index.spec.tsx
  packages/design/components/Input/index.tsx
  packages/design/components/Input/style/index.less
  packages/design/components/Select/style/index.less
  packages/website/src/pages/index/subject/[id]/wiki/common.module.less
  packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx
  packages/website/src/pages/login/index.module.less
  packages/website/src/pages/login/index.tsx
Labels: size/M, waiting-opened-48h

#349 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, waiting-opened-48h

#353 feat(design): input text prefix
  packages/design/components/Input/Input.stories.tsx
  packages/design/components/Input/style/index.less
Labels: size/XS, waiting-opened-48h

#351 feat: compact form
  packages/design/components/EditorForm/Editor.tsx
  packages/design/components/EditorForm/index.tsx
  packages/design/components/EditorForm/style/index.less
  packages/design/components/Form/Form.stories.tsx
  packages/design/components/Form/__test__/Form.spec.tsx
  packages/design/components/Form/__test__/__snapshots__/Form.spec.tsx.snap
  packages/design/components/Form/index.tsx
  packages/design/components/Form/style/index.less
  packages/design/components/Input/index.tsx
  packages/design/components/Input/style/index.less
Labels: size/M, waiting-review

#321 feat(website): add line number in toast when error occurred
  packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx
Labels: size/XS

#356 feat: add link back to subject on wiki page
  packages/website/src/pages/index/subject/[id]/components/WikiLayout.module.less
  packages/website/src/pages/index/subject/[id]/components/WikiLayout.tsx
Labels: size/XS, waiting-opened-48h

#320 feat: group new topic page
  packages/website/src/pages/index/group/[name].tsx
  packages/website/src/pages/index/group/[name]/__tests__/index.spec.tsx
  packages/website/src/pages/index/group/[name]/__tests__/members.spec.tsx
  packages/website/src/pages/index/group/[name]/components/NewTopicForm.module.less
  packages/website/src/pages/index/group/[name]/components/NewTopicForm.tsx
  packages/website/src/pages/index/group/[name]/index.tsx
  packages/website/src/pages/index/group/[name]/index/forum.tsx
  packages/website/src/pages/index/group/[name]/index/index.tsx
  packages/website/src/pages/index/group/[name]/index/members.tsx
  packages/website/src/pages/index/group/[name]/index/style.module.less
  packages/website/src/pages/index/group/[name]/new_topic.tsx
  packages/website/src/pages/index/group/[name]/new_topic/index.tsx
  packages/website/src/pages/index/group/[name]/new_topic/style.module.less
  packages/website/src/pages/index/group/components/GroupLayout.tsx
  packages/website/src/pages/index/group/components/GroupNavigation.module.less
  packages/website/src/pages/index/group/components/GroupNavigation.tsx
  packages/website/src/pages/index/group/topic/[id]/index.tsx
Labels: size/XL, waiting-review

#362 ci: disable PR review request
  .github/mergify.yml
Labels: size/XS, waiting-review

#357 feat(Editor): word count
  packages/design/components/EditorForm/Editor.tsx
  packages/design/components/EditorForm/__test__/Editor.spec.tsx
  packages/design/components/EditorForm/__test__/__snapshots__/Editor.spec.tsx.snap
  packages/design/components/EditorForm/__test__/__snapshots__/EditorForm.test.tsx.snap
  packages/design/components/EditorForm/style/index.less
  packages/design/components/Form/__test__/__snapshots__/Form.spec.tsx.snap
Labels: size/S, waiting-opened-48h

#367 ci: require 2 approval to auto-merging
  .github/mergify.yml
  CONTRIBUTING.md
Labels: size/S, waiting-opened-48h

#359 feat: redirect to last page after successful login
  packages/website/src/pages/login/index.spec.tsx
  packages/website/src/pages/login/index.tsx
Labels: size/S, waiting-opened-48h

#366 refactor(design): compact form style
  packages/design/components/EditorForm/Editor.tsx
  packages/design/components/EditorForm/index.tsx
  packages/design/components/EditorForm/style/index.less
  packages/design/components/Form/Form.stories.tsx
  packages/design/components/Form/__test__/Form.spec.tsx
  packages/design/components/Form/__test__/__snapshots__/Form.spec.tsx.snap
  packages/design/components/Form/style/index.less
  packages/design/components/Input/index.tsx
  packages/design/components/Input/style/index.less
  packages/design/theme/base.less
Labels: size/M

#365 fix: hide new post form & button if not logged in
  packages/website/src/pages/index/group/[name]/index/forum.tsx
  packages/website/src/pages/index/group/[name]/index/index.tsx
  packages/website/src/pages/index/group/components/GroupLayout.tsx
  packages/website/src/pages/index/group/topic/[id]/index.tsx
Labels: size/XS

#363 feat: BBcode editor disable horizontal resizing
  packages/design/components/EditorForm/__test__/__snapshots__/EditorForm.test.tsx.snap
  packages/design/components/EditorForm/index.tsx
  packages/design/components/EditorForm/style/index.less
  packages/design/components/Form/Form.stories.tsx
  packages/design/components/Form/__test__/__snapshots__/Form.spec.tsx.snap
  packages/design/components/Form/style/index.less
  packages/design/components/Topic/style/Comment.less
  packages/design/theme/base.less
  packages/design/theme/mixins.less
  packages/design/theme/variables.less
  packages/website/src/pages/index/group/[name]/components/NewTopicForm.module.less
  packages/website/src/pages/index/group/[name]/components/NewTopicForm.tsx
  packages/website/src/pages/index/group/topic/[id]/index.module.less
Labels: size/M

#414 fix: duplicate key rendering `(bgm23)\n(bgm13)`
  packages/utils/bbcode/__test__/__snapshots__/react.test.tsx.snap
  packages/utils/bbcode/__test__/react.test.tsx
  packages/utils/bbcode/react.tsx
Labels: size/S, waiting-approval

#413 refactor: plain text link button
  packages/design/components/Button/__test__/Button.test.tsx
  packages/design/components/Button/__test__/__snapshots__/Button.test.tsx.snap
  packages/design/components/Button/button.stories.tsx
  packages/design/components/Button/index.tsx
  packages/design/components/Button/style/index.less
  packages/website/src/pages/index/group/[name]/index/index.tsx
  packages/website/src/pages/index/group/common.module.less
  packages/website/src/pages/index/group/components/GroupLayout.tsx
  packages/website/src/pages/index/subject/[id]/wiki/common.module.less
  packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx
Labels: size/M, waiting-approval

#395 tests: use vitest
  .eslintignore
  .eslintrc.js
  .stylelintignore
  babel.config.js
  jest-setup.ts
  jest.config.js
  package.json
  packages/design/.storybook/.babelrc
  packages/design/components/Button/__test__/Button.test.tsx
  packages/design/components/Button/__test__/__snapshots__/Button.test.tsx.snap
  packages/design/components/EditorForm/__test__/Editor.spec.tsx
  packages/design/components/EditorForm/__test__/EditorForm.test.tsx
  packages/design/components/EditorForm/__test__/Toolbox.spec.tsx
  packages/design/components/EditorForm/__test__/__snapshots__/Editor.spec.tsx.snap
  packages/design/components/EditorForm/__test__/__snapshots__/EditorForm.test.tsx.snap
  packages/design/components/EditorForm/__test__/__snapshots__/Toolbox.spec.tsx.snap
  packages/design/components/Form/__test__/Form.spec.tsx
  packages/design/components/Form/__test__/__snapshots__/Form.spec.tsx.snap
  packages/design/components/Image/__test__/__snapshots__/index.spec.tsx.snap
  packages/design/components/Input/__test__/__snapshots__/index.spec.tsx.snap
  packages/design/components/Menu/__test__/Menu.spec.tsx
  packages/design/components/Pagination/__test__/__snapshots__/index.spec.tsx.snap
  packages/design/components/Pagination/__test__/index.spec.tsx
  packages/design/components/Select/__test__/__snapshots__/Select.spec.tsx.snap
  packages/design/components/Tab/__test__/Tab.spec.tsx
  packages/design/components/Tab/__test__/__snapshots__/Tab.spec.tsx.snap
  packages/design/components/Toast/__test__/Toast.spec.tsx
  packages/design/components/Toast/__test__/ToastContainer.spec.tsx
  packages/design/components/Topic/__test__/Comment.spec.tsx
  packages/design/components/Topic/__test__/__snapshots__/Comment.spec.tsx.snap
  packages/design/components/Typography/__test__/__snapshots__/Link.spec.tsx.snap
  packages/design/components/Typography/__test__/__snapshots__/Texts.spec.tsx.snap
  packages/utils/bbcode/__test__/__snapshots__/html.test.ts.snap
  packages/utils/bbcode/__test__/__snapshots__/react.test.tsx.snap
  packages/utils/wiki.spec.ts
  packages/website/package.json
  packages/website/src/components/PageRoutes/auth.spec.tsx
  packages/website/src/hooks/__snapshots__/use-user.spec.tsx.snap
  packages/website/src/hooks/use-user.spec.tsx
  packages/website/src/pages/components/UserHome.spec.tsx
  packages/website/src/pages/index/group/[name]/__tests__/index.spec.tsx
  packages/website/src/pages/index/group/[name]/__tests__/members.spec.tsx
  packages/website/src/pages/login/index.spec.tsx
  packages/website/tsconfig.json
  pnpm-lock.yaml
  tests/__mocks__/svg.js
  tests/env.d.ts
  tests/setup.ts
  tests/website.ts
  tsconfig.json
  vitest.config.ts
Labels: size/L, waiting-approval

#415 refactor: collapsible content
  packages/design/components/CollapsibleContent/CollapsibleContent.stories.tsx
  packages/design/components/CollapsibleContent/__test__/CollapsibleContent.test.tsx
  packages/design/components/CollapsibleContent/__test__/__snapshots__/CollapsibleContent.test.tsx.snap
  packages/design/components/CollapsibleContent/index.tsx
  packages/design/components/CollapsibleContent/style/index.less
  packages/design/index.tsx
  packages/icons/assets/arrow-down-circle.svg
  packages/icons/assets/arrow-up-circle.svg
  packages/website/src/assets/down-arrow.svg
  packages/website/src/assets/right-arrow.svg
  packages/website/src/assets/up-arrow.svg
  packages/website/src/hooks/use-group.ts
  packages/website/src/pages/index/group/[name]/index/index.tsx
  packages/website/src/pages/index/group/components/ClampableContent.module.less
  packages/website/src/pages/index/group/components/ClampableContent.tsx
  packages/website/src/pages/index/group/components/GroupInfo.tsx
Labels: size/L, waiting-approval

#418 style: remove deprecated rules
  .stylelintrc.js
Labels: size/XS, waiting-approval

#419 chore: update LICENSE date
  LICENSE
Labels: size/XS, waiting-approval

#369 feat: edit group topic
  packages/website/src/hooks/use-group-topic.ts
  packages/website/src/pages/index/group/[name]/index/forum.tsx
  packages/website/src/pages/index/group/[name]/index/index.tsx
  packages/website/src/pages/index/group/[name]/new_topic/index.tsx
  packages/website/src/pages/index/group/components/TopicForm.module.less
  packages/website/src/pages/index/group/components/TopicForm.tsx
  packages/website/src/pages/index/group/topic/[id]/edit.module.less
  packages/website/src/pages/index/group/topic/[id]/edit.tsx
  packages/website/src/pages/index/group/topic/[id]/index.module.less
  packages/website/src/pages/index/group/topic/[id]/index.tsx
Labels: size/M, waiting-approval

#421 feat: title attr for TopicsTable
  packages/website/src/pages/index/group/[name]/components/TopicsTable.tsx
Labels: size/XS, waiting-approval

#432 chore: fix npm scripts bypass args
  package.json
Labels: size/XS, waiting-approval

#422 refactor: change submit buttons size to large
  packages/design/components/EditorForm/__test__/__snapshots__/EditorForm.test.tsx.snap
  packages/design/components/EditorForm/index.tsx
  packages/design/components/EditorForm/style/index.less
  packages/design/components/Form/__test__/__snapshots__/Form.spec.tsx.snap
Labels: size/XS, waiting-approval
