Repository bangumi/frontend, pull requests merged in 2023-08, with the labels that each got.

#610 ci: fix PR preview URL
  .github/scripts/upload-preview.mts
Labels: size/XS

#611 ci: use cloudflare pages for PR preview
  .github/scripts/upload-preview.mts
  .github/workflows/build.yml
  .github/workflows/preview.yaml
  .github/workflows/storybook-build.yml
  _functions/p1/[[catchall]].js
  _functions/readme.md
  packages/website/public/.gitkeep
  packages/website/public/_redirects
Labels: size/M, waiting-approval

#608 refactor(website): refactor E2E test
  .gitignore
  packages/website/e2e/.gitignore
  packages/website/e2e/common/login.ts
  packages/website/e2e/setup/auth.setup.ts
  packages/website/e2e/specs/404.spec.ts
  packages/website/e2e/specs/group.spec.ts
  packages/website/e2e/specs/login.spec.ts
  packages/website/e2e/specs/main.spec.ts
  packages/website/package.json
  packages/website/playwright.config.ts
  pnpm-lock.yaml
Labels: size/S, waiting-approval
