Repository bangumi/frontend, pull requests merged in 2025-02, with the labels that each got.

#656 fix: backend incompatible changes
  .github/mergify.yml
  .github/workflows/e2e-test.yml
  packages/client/api.yaml
  packages/client/client.ts
  packages/client/common.ts
  packages/client/group.ts
  packages/client/topic.ts
  packages/client/types/index.ts
  packages/design/components/Topic/Comment.tsx
  packages/design/components/Topic/ReplyForm.tsx
  packages/design/components/Topic/__test__/Comment.spec.tsx
  packages/design/components/Topic/__test__/__snapshots__/Comment.spec.tsx.snap
  packages/design/components/Topic/__test__/fixtures/repliesComment.json
  packages/design/components/Topic/__test__/fixtures/singleComment.json
  packages/design/components/Topic/__test__/fixtures/specialComment.json
  packages/design/components/Topic/__test__/fixtures/user.json
  packages/website/.gitignore
  packages/website/e2e/setup/auth.setup.ts
  packages/website/src/components/PageRoutes/auth.spec.tsx
  packages/website/src/components/PageRoutes/auth.tsx
  packages/website/src/hooks/use-group-members.ts
  packages/website/src/hooks/use-group-post.ts
  packages/website/src/hooks/use-group-topic.ts
  packages/website/src/hooks/use-group-topics.ts
  packages/website/src/hooks/use-group.ts
  packages/website/src/hooks/use-user.tsx
  packages/website/src/pages/index/group/[name]/__tests__/fixtures/recent-topics.json
  packages/website/src/pages/index/group/[name]/__tests__/fixtures/sandbox-members.json
  packages/website/src/pages/index/group/[name]/__tests__/fixtures/sandbox-mod-member.json
  packages/website/src/pages/index/group/[name]/__tests__/fixtures/sandbox.json
  packages/website/src/pages/index/group/[name]/__tests__/index.spec.tsx
  packages/website/src/pages/index/group/[name]/__tests__/members.spec.tsx
  packages/website/src/pages/index/group/[name]/components/TopicsTable.tsx
  packages/website/src/pages/index/group/[name]/index/forum.tsx
  packages/website/src/pages/index/group/[name]/index/index.tsx
  packages/website/src/pages/index/group/[name]/index/members.tsx
  packages/website/src/pages/index/group/[name]/new_topic/index.tsx
  packages/website/src/pages/index/group/components/GroupActions.tsx
  packages/website/src/pages/index/group/components/GroupHeader.tsx
  packages/website/src/pages/index/group/components/GroupInfo.tsx
  packages/website/src/pages/index/group/components/GroupLayout.tsx
  packages/website/src/pages/index/group/components/GroupNavigation.tsx
  packages/website/src/pages/index/group/components/TopicForm.tsx
  packages/website/src/pages/index/group/reply/[id]/edit.tsx
  packages/website/src/pages/index/group/topic/[id]/components/GroupTopicHeader.tsx
  packages/website/src/pages/index/group/topic/[id]/index.tsx
Labels: size/XXL, waiting-approval

#664 ci: upgrade setup-js-env to use corepack
  .github/actions/setup-js-env/action.yaml
Labels: size/S

#668 style: upgrade prettier
  package.json
  packages/design/components/Topic/Comment.tsx
  packages/website/src/components/ErrorBoundary/index.tsx
  pnpm-lock.yaml
Labels: size/XS, waiting-approval

#689 ci: upgrade mergify config
  .github/mergify.yml
Labels: size/XS, waiting-approval

#735 fix: server request id header
  packages/website/src/components/ErrorBoundary/index.tsx
Labels: size/XS, waiting-approval

#742 ci: use latest corepack
  .github/actions/setup-js-env/action.yaml
Labels: size/XS, waiting-approval

#744 Add typescript-plugin-css-modules
  packages/website/package.json
  packages/website/tsconfig.json
  pnpm-lock.yaml
Labels: size/XS, waiting-approval, DX

#749 chore: update api spec
  packages/client/api.yaml
  packages/client/client.ts
  packages/client/group.ts
  packages/client/package.json
  packages/client/types/index.ts
  packages/website/src/hooks/use-group-members.ts
  packages/website/src/hooks/use-group.ts
  packages/website/src/pages/index/group/[name]/index/members.tsx
  packages/website/src/pages/index/group/components/GroupActions.tsx
  packages/website/src/pages/index/group/components/GroupHeader.tsx
  packages/website/src/pages/index/group/components/GroupInfo.tsx
  packages/website/src/pages/index/group/components/GroupLayout.tsx
  packages/website/src/pages/index/group/components/GroupNavigation.tsx
  packages/website/src/pages/index/group/topic/[id]/components/GroupTopicHeader.tsx
  packages/website/src/pages/index/group/topic/[id]/index.tsx
  packages/website/src/shared/wiki.ts
  pnpm-lock.yaml
Labels: size/XXL, waiting-approval
